// Archivo centralizado para importar todas las rutas
import './auth.js'
import './countries.js'
import './locations.js'
import './account.js'
import './companies.js'
import './unidades-residenciales.js'
import './user.js'
import './roles.js'
import './torres-bloques.js'
import './apartamentos.js'
import './agencias.js'
import './residentes.js'
import './propietarios.js'
import './tipos-vehiculos.js'
import './vehiculos-apartamento.js'